source "https://rubygems.org"

gem "roda"
gem "sequel"
gem "sqlite3"
gem "phlex"
gem "puma"
gem "json_schemer"
gem "bcrypt"
gem "rack-session"
gem "rackup"
gem "stripe"

group :development do
  gem "rerun"
  gem "foreman"
end

group :test do
  gem "rake"
  gem "minitest"
  gem "rack-test"
end
